server:
  port: 8000
  servlet:
    context-path: /     # 스프링 시큐리티를 위해 /blog가 아닌 / 사용
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl       # @Entity가 동작할때, 변수명 그대로 테이블에 피드로 만든다
                                                   # 만약, org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy로 사용하게 된다면 
                                                   # User 테이블에 myNmae 이라고 작성했을 경우, my_name으로 피드에 저장된다.
      use-new-id-generator-mappings: false
    #show-sql: true                             # console 창에 내용이 보이도록
    properties:                               # console 창에 보이는 내용을 한 줄이 아닌 보기 쉽도록 
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

cos:
  key: cos1234
